In [ ]:
import tensorflow as tf
from te
8nsorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    'Today is a sunny day',
    'Today is a rainy day'
]

tokenizer = Tokenizer(num_words = 100)
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

{'today': 1, 'is': 2, 'a': 3, 'day': 4, 'sunny': 5, 'rainy': 6}


In [ ]:
sentence = [
    'Today is a sunny day',
    'Today is a rainy day',
    'is It sunny today?'
]
tokenizer = Tokenizer(num_words = 100)
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index

sequence = tokenizer.texts_to_sequences(sentence)
print(sequence)

[[1, 2, 3, 4, 5], [1, 2, 3, 6, 5], [2, 7, 4, 1]]


In [ ]:
test_data = [
    'Today is a snowy day',
    'Will it be rainy tomorrow?'
]

In [ ]:
test_sequences = tokenizer.texts_to_sequences(test_data)
print(word_index)
print(test_sequences)

{'today': 1, 'is': 2, 'a': 3, 'sunny': 4, 'day': 5, 'rainy': 6, 'it': 7}
[[1, 2, 3, 5], [7, 6]]


In [ ]:
tokenizer = Tokenizer(num_words=100, oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

test_sequences = tokenizer.texts_to_sequences(test_data)
print(word_index)
print(test_sequences)


{'<OOV>': 1, 'today': 2, 'is': 3, 'a': 4, 'day': 5, 'sunny': 6, 'rainy': 7}
[[2, 3, 4, 1, 5], [1, 1, 1, 7, 1]]


In [ ]:
sentences = [
    'Today is a sunny day',
    'Today is a rainy day',
    'is It sunny today?',
    'I really enjoyed walking in the snow today'
]

In [ ]:
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentence)
print(sequences)

[[2, 3, 4, 6, 5], [2, 3, 4, 7, 5], [3, 8, 6, 2], [9, 10, 11, 12, 13, 14, 15, 2]]


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
padded = pad_sequences(sequences)
print(padded)

[[ 0  0  0  2  3  4  6  5]
 [ 0  0  0  2  3  4  7  5]
 [ 0  0  0  0  3  8  6  2]
 [ 9 10 11 12 13 14 15  2]]


In [ ]:
padded = pad_sequences(sequences, padding = 'post')
print(padded)

[[ 2  3  4  6  5  0  0  0]
 [ 2  3  4  7  5  0  0  0]
 [ 3  8  6  2  0  0  0  0]
 [ 9 10 11 12 13 14 15  2]]


In [ ]:
padded = pad_sequences(sequences, padding = 'post', maxlen = 6)
print(padded)

[[ 2  3  4  6  5  0]
 [ 2  3  4  7  5  0]
 [ 3  8  6  2  0  0]
 [11 12 13 14 15  2]]


In [ ]:
padded = pad_sequences(sequences, padding = 'post', maxlen= 6, truncating = 'post')
print(padded)

[[ 2  3  4  6  5  0]
 [ 2  3  4  7  5  0]
 [ 3  8  6  2  0  0]
 [ 9 10 11 12 13 14]]


In [ ]:
#idbm 데이터

import tensorflow_datasets as tfds

imdb_sentences = []
train_data = tfds.as_numpy(tfds.load('imdb_reviews', split = 'train'))

for item in train_data:
  imdb_sentences.append(str(item['text']))

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete4QE14D/imdb_reviews-train.tfrecord…

Generating test examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete4QE14D/imdb_reviews-test.tfrecord*…

Generating unsupervised examples...:   0%|          | 0/50000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incomplete4QE14D/imdb_reviews-unsupervised.t…

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [ ]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words = 5000)
tokenizer.fit_on_texts(imdb_sentences)
sequences = tokenizer.texts_to_sequences(imdb_sentences)

In [ ]:
print(tokenizer.word_index)

{'the': 1, 'and': 2, 'a': 3, 'of': 4, 'to': 5, 'is': 6, 'br': 7, 'in': 8, 'it': 9, 'i': 10, 'this': 11, 'that': 12, 'was': 13, 'as': 14, 'for': 15, 'with': 16, 'movie': 17, 'but': 18, 'film': 19, "'s": 20, 'on': 21, 'you': 22, 'not': 23, 'are': 24, 'his': 25, 'he': 26, 'have': 27, 'be': 28, 'one': 29, 'all': 30, 'at': 31, 'by': 32, 'they': 33, 'an': 34, 'who': 35, 'so': 36, 'from': 37, 'like': 38, 'her': 39, "'t": 40, 'or': 41, 'just': 42, 'there': 43, 'about': 44, 'out': 45, "'": 46, 'has': 47, 'if': 48, 'some': 49, 'what': 50, 'good': 51, 'more': 52, 'very': 53, 'when': 54, 'she': 55, 'up': 56, 'can': 57, 'b': 58, 'time': 59, 'no': 60, 'even': 61, 'my': 62, 'would': 63, 'which': 64, 'story': 65, 'only': 66, 'really': 67, 'see': 68, 'their': 69, 'had': 70, 'were': 71, 'me': 72, 'well': 73, 'we': 74, 'than': 75, 'much': 76, 'been': 77, 'get': 78, 'bad': 79, 'will': 80, 'people': 81, 'do': 82, 'also': 83, 'other': 84, 'into': 85, 'because': 86, 'great': 87, 'first': 88, 'him': 89, 'how'

In [ ]:
from bs4 import BeautifulSoup
import string

stopwords = ["a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at",
             "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do",
             "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having",
             "he", "hed", "hes", "her", "here", "heres", "hers", "herself", "him", "himself", "his", "how",
             "hows", "i", "id", "ill", "im", "ive", "if", "in", "into", "is", "it", "its", "itself",
             "lets", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought",
             "our", "ours", "ourselves", "out", "over", "own", "same", "she", "shed", "shell", "shes", "should",
             "so", "some", "such", "than", "that", "thats", "the", "their", "theirs", "them", "themselves", "then",
             "there", "theres", "these", "they", "theyd", "theyll", "theyre", "theyve", "this", "those", "through",
             "to", "too", "under", "until", "up", "very", "was", "we", "wed", "well", "were", "weve", "were",
             "what", "whats", "when", "whens", "where", "wheres", "which", "while", "who", "whos", "whom", "why",
             "whys", "with", "would", "you", "youd", "youll", "youre", "youve", "your", "yours", "yourself",
             "yourselves"]


In [ ]:
table = str.maketrans('', '', string.punctuation)

imdb_sentences = []
train_data = tfds.as_numpy(tfds.load('imdb_reviews', split = 'train'))
for item in train_data:
  sentence = str(item['text'].decode('UTF-8').lower())
  sentece = sentence.replace(",", " , ")
  sentence = sentence.replace(".", " . ")
  sentence = sentence.replace("-", " - ")
  sentence = sentence.replace("/", " / ")
  soup = BeautifulSoup(sentence)
  sentece = soup.get_text()
  words = sentence.split()
  filtered_sentence = ""
  for word in words:
    word = word.translate(table)
    if word not in stopwords:
      filtered_sentence = filtered_sentence + word + " "
  imdb_sentences.append(filtered_sentence)

tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words = 25000)
tokenizer.fit_on_texts(imdb_sentences)


<ipython-input-61-faf7e07602b1>:11: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(sentence)


In [ ]:
print(tokenizer.word_index)

{'br': 1, 'movie': 2, 'film': 3, 'not': 4, 'one': 5, 'like': 6, 'just': 7, 'good': 8, 'no': 9, 'time': 10, 'even': 11, 'story': 12, 'really': 13, 'see': 14, 'can': 15, 'much': 16, 'get': 17, 'bad': 18, 'will': 19, 'also': 20, 'people': 21, 'first': 22, 'great': 23, 'dont': 24, 'made': 25, 'movies': 26, 'make': 27, 'way': 28, 'films': 29, 'characters': 30, 'think': 31, 'watch': 32, 'two': 33, 'character': 34, 'many': 35, 'seen': 36, 'plot': 37, 'life': 38, 'never': 39, 'acting': 40, 'little': 41, 'love': 42, 'best': 43, 'show': 44, 'know': 45, 'off': 46, 'ever': 47, 'better': 48, 'end': 49, 'still': 50, 'man': 51, 'say': 52, 'scene': 53, 'scenes': 54, 'go': 55, 'something': 56, 'back': 57, 'real': 58, 'watching': 59, 'years': 60, 'doesnt': 61, 'now': 62, 'actors': 63, 'though': 64, 'old': 65, 'thing': 66, 'didnt': 67, 'work': 68, 'another': 69, 'new': 70, 'nothing': 71, 'funny': 72, 'actually': 73, 'makes': 74, '10': 75, 'director': 76, 'look': 77, 'find': 78, 'going': 79, 'part': 80, '

In [ ]:
sentences = [
    'Today is a sunny day',
    'Today is a rainy day',
    'Is it sunny today?'
]
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[517, 5166, 148], [517, 6486, 148], [5166, 517]]


In [ ]:
reverse_word_index = dict(
    [(value, key) for (key, value) in tokenizer.word_index.items()]
)

decoded_review = ' '.join([reverse_word_index.get(i, '?') for i in sequences[0]])
print(decoded_review)

today sunny day
